import Link from "next/link";
import EditorialArticle from "../../editorial-article";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata("/sobre-el-juego");
export default function AboutPage() {
  return <EditorialArticle title="Sobre El Peaje" intro="Un juego de predicciones con baraja francesa convertido en un recorrido de cartas, retrocesos y peajes que puedes abrir directamente en el navegador.">
    <section><h2>Qué propone el juego</h2><p>La partida comienza con una carta visible. A partir de ella recorres preguntas de mayor o menor, forma del palo, color y palo exacto. Acertar permite avanzar; fallar te devuelve hacia una pregunta anterior. Entre preguntas hay peajes: pausas que el grupo interpreta con puntos, conversación o un reto acordado.</p><p>No construyes una mano ni compites por llevarte cartas como en otros juegos de baraja. Aquí decides sobre una carta todavía oculta y gestionas el recorrido que produce cada resultado. Las cartas reveladas se retiran del mazo, de modo que recordar lo que salió aporta información.</p></section>
    <section><h2>Del recorrido con cartas a la pantalla</h2><p>El punto de partida del proyecto es esa dinámica de predicción y peajes. La adaptación web asume el reparto y la posición para poder empezar sin preparar una mesa ni instalar software. No hace falta registrarse: una persona puede aprender sola y un grupo puede compartir el móvil.</p><p>La web separa la partida de las explicaciones. Quien conoce las reglas entra a jugar; quien necesita contexto puede consultar ejemplos, probabilidades y modos sin interrumpir una partida. El objetivo es que cada pantalla resuelva una necesidad concreta.</p></section>
    <section><h2>Filosofía de diseño</h2><p>La identidad visual mezcla cartas con señales, billetes y una cabina de carretera. Esa metáfora también organiza la partida: una ruta visible y pasos que requieren confirmación. Los mensajes conservan un tono informal, mientras las guías explican con precisión qué significa cada resultado.</p><p>El peaje es flexible porque la diversión no depende de una bebida o una penalización concreta. La web marca el cruce, pero no exige alcohol ni mide cuánto consume nadie. Podéis acordar preguntas o puntos y permitir que cualquiera omita un reto.</p><p>Se da prioridad a jugar sin cuentas y con controles directos. El estado vive en memoria del navegador: esa sencillez también tiene un límite, porque recargar o cerrar la pestaña pierde la partida.</p></section>
    <section><h2>Cómo ha evolucionado</h2><p>El código actual amplía el recorrido básico con seis variantes: clásico, puntos, cooperativo, turnos rápidos, peaje seguro y La patata. La dificultad cambia las preguntas y los peajes; La patata difícil añade par o impar. Turnos rápidos guarda dos recorridos independientes y La patata permite compartir uno entre tres y ocho números de jugador.</p><p>El proyecto incluye además estilos de carta, un QR para compartir el sitio y versiones en varios idiomas. Esta capa editorial explica decisiones y cálculos específicos del motor. Describe funciones presentes; no anuncia aplicaciones o servicios futuros como si estuvieran disponibles.</p></section>
    <section><h2>Quién mantiene el proyecto</h2><p>El código del proyecto se publica en el repositorio <a href="https://github.com/seryio2004/peaje" target="_blank" rel="noreferrer">seryio2004/peaje</a>. Allí se puede consultar su historial y comunicar incidencias. Para dudas o sugerencias también está disponible <Link prefetch={false} href="/contacto">el contacto por correo</Link>.</p><p>Esta web no publica una biografía del desarrollador ni atribuye un origen histórico al juego de mesa. La información de mantenimiento se limita al proyecto y a sus canales de contacto verificables en el propio sitio.</p></section>
    <section><h2>La tecnología detrás de la baraja</h2><p>Next.js, React y TypeScript permiten separar las páginas estáticas de la interacción. El sitio se exporta a HTML y recursos que sirve Cloudflare; la lógica de cartas se ejecuta en el navegador. No hay un servidor de partidas ni una sala compartida entre móviles.</p><p>En <Link prefetch={false} href="/desarrollo">la explicación técnica</Link> puedes ver cómo se mezclan las cartas y se gestionan las fases. Si prefieres empezar por las decisiones del jugador, consulta <Link prefetch={false} href="/probabilidades">las probabilidades</Link>.</p></section>
  </EditorialArticle>;
}
