import EditorialArticle from "../../editorial-article";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata("/variantes");
const variants = [
  { title: "Una ruta para romper el hielo", players: "1 o 2", setup: "Clásico, dificultad fácil. Elegid una pregunta breve como peaje.", rules: "Jugad una sola partida hasta completar la ruta o agotar el mazo. Si sois dos, una persona predice en voz alta y la otra revela y valida; intercambiad papeles en la siguiente partida.", time: "Reservad 5–10 minutos", difference: "Reduce la sesión a un recorrido de tres preguntas. No impone un límite de tiempo al motor: si la partida se alarga, podéis cerrarla sin anotarla como victoria." },
  { title: "Duelo de dos rutas", players: "2", setup: "Turnos rápidos, misma dificultad para ambos. Acordad antes si gana quien complete primero.", rules: "Cada persona conserva su ruta y baraja. Al acertar sigue; al fallar cede el turno. Para una revancha, empezad una partida nueva e intercambiad quién comienza. Anotad el resultado fuera de la web.", time: "Reservad 10–20 minutos para ida y revancha", difference: "Usa el modo de turnos ya implementado. El objetivo de la sesión lo acordáis vosotros; no añade un ranking ni sincroniza mazos." },
  { title: "La patata con reparto de participación", players: "3–8", setup: "La patata normal. Asignad los números de jugador y colocad el móvil donde todos vean las cartas.", rules: "Cuando se habilite un pase, elegid a quien menos haya respondido. Si hay empate, seguid el orden de los números. Llevad la cuenta en papel. Un fallo conserva el móvil y un peaje debe completarse antes de cederlo.", time: "Reservad 10–15 minutos por sesión", difference: "Añade un acuerdo social al pase opcional. No garantiza un número igual de turnos, porque las cartas de pase y los aciertos siguen siendo necesarios." },
  { title: "Mesa por equipos", players: "4–8, en dos equipos", setup: "Cooperativo, dificultad media. Cada equipo juega una partida nueva; anotad quién llega al final y con cuántos fallos.", rules: "En cada equipo una persona pulsa y todos debaten la predicción antes de revelar. Si ambos completan, gana quien tenga menos fallos; si empatan, compartid el resultado. Si ninguno completa, repetid en fácil. La web termina el reto al sexto fallo.", time: "Reservad 15–25 minutos para las dos partidas", difference: "Los equipos y la comparación se gestionan fuera del juego. El modo cooperativo sigue teniendo una sola ruta y no identifica a cada miembro." },
  { title: "Peajes de conversación", players: "1–8 según la configuración", setup: "Para uno o dos, Peaje seguro. Para 3–8, La patata. Preparad cinco preguntas sencillas: una recomendación, un recuerdo divertido o una preferencia.", rules: "En cada cruce escoged una pregunta y contestadla o pasad sin explicar el motivo. Confirmad el peaje para continuar. Evitad tareas físicas o preguntas personales que alguien no quiera responder.", time: "Reservad 10–20 minutos, según las conversaciones", difference: "Sustituye la consecuencia social del peaje por conversación. No cambia las cartas, los retrocesos ni la necesidad de confirmar cada cruce." },
  { title: "Tres intentos por puntos", players: "2–8 por turnos, con un solo operador", setup: "Por puntos, dificultad media. Preparad una hoja con tres columnas de resultados para cada participante.", rules: "Cada persona inicia tres partidas nuevas en configuración de un jugador. Para cada ruta completada apuntad fallos + 2 × peajes. Ordenad primero por número de rutas completadas, después por menor suma de puntos de esas rutas. Marcad los mazos agotados como no completados; si hay empate, compartid puesto.", time: "Reservad 5–10 minutos por intento; con grupos puede ser una sesión larga", difference: "Propone una clasificación manual que distingue completar de agotar el mazo. No presenta un marcador online ni equipara barajas diferentes como si fueran idénticas." },
];
export default function VariantsPage() {
  return <EditorialArticle title="Variantes para organizar una sesión" intro="Seis propuestas de mesa que usan las opciones actuales de El Peaje. Son acuerdos para vuestra sesión, no nuevos botones ni funciones pendientes.">
    <section><h2>Antes de elegir</h2><p>El motor conserva sus reglas: acertar avanza, fallar retrocede y cada cruce de peaje requiere confirmación. Los tiempos siguientes son presupuestos para organizaros, no duraciones medidas ni límites automáticos. Los fallos, el agotamiento del mazo y la conversación pueden alargar o acortar la sesión.</p></section>
    {variants.map(variant => <section key={variant.title}><h2>{variant.title}</h2><p><strong>Participantes:</strong> {variant.players}. <strong>Tiempo orientativo:</strong> {variant.time}.</p><h3>Preparación</h3><p>{variant.setup}</p><h3>Reglas de sesión</h3><p>{variant.rules}</p><h3>Qué cambia</h3><p>{variant.difference}</p></section>)}
    <section><h2>Si sois más de ocho</h2><p>La patata admite como máximo ocho números de jugador. Para una reunión mayor, formad mesas separadas de hasta ocho personas o jugad por equipos con un operador. Cada móvil abre una partida independiente; no hay una sala multijugador compartida entre dispositivos.</p></section>
  </EditorialArticle>;
}
