import Link from "next/link";
import EditorialArticle from "../../editorial-article";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata("/estrategia");
export default function StrategyPage() {
  return <EditorialArticle title="Estrategia y decisiones en El Peaje" intro="Una buena elección usa la información disponible. Puede mejorar un intento, pero no garantiza superar una ruta que también depende del azar.">
    <section><h2>Qué sabes antes de responder</h2><p>Conoces la pregunta, la posición, las cartas reveladas que recuerdes y los fallos y peajes acumulados. En mayor o menor, el motor busca la última carta de una posición anterior; en la primera pregunta utiliza siempre la carta inicial. Una carta que acaba de salir en esa primera posición no sustituye la referencia inicial del siguiente intento.</p><p>El orden del mazo y las cartas de pase de La patata permanecen ocultos en la interfaz. Los estilos de carta cambian su aspecto, no su valor. No hay una elección de apuesta ni un botón que reduzca el retroceso a cambio de puntos.</p></section>
    <section><h2>Cartas extremas: aprovecha la asimetría</h2><p>Con un 2 de referencia, menor es imposible. Mayor es la elección con más posibilidades, aunque otro 2 sigue siendo fallo. Con un as, elige menor por la misma razón. Con una K al primer intento hay 44 cartas menores y solo 4 mayores: una carta cercana al extremo ofrece una diferencia grande, pero tampoco garantiza acertar.</p><p>Ejemplo: empieza un 2♥, eliges mayor y sale 2♠. Has fallado; no es un error del juego. Tras continuar sigues en la primera pregunta, con 2♥ como referencia y una carta menos en el mazo. Los dos doses restantes siguen siendo resultados perdedores.</p></section>
    <section><h2>Cartas centrales: el historial decide</h2><p>Con un 8 inicial y ningún otro dato, mayor y menor tienen el mismo número de cartas favorables. No hay una opción secreta mejor. Si ya salieron cuatro cartas de valores inferiores al 8 y ninguna superior, quedan más cartas mayores que menores; elegir mayor aprovecha esa información.</p><p>No confundas recordar cartas con creer que «ya toca» un color. La ventaja aparece porque las cartas salen sin reposición: para justificarla hay que contar cuántas quedan. Si faltan cartas en tu recuerdo, usa la tabla inicial como orientación, no como probabilidad exacta del turno.</p></section>
    <section><h2>El riesgo del fallo depende de la posición</h2><p>La web no permite elegir cuánto arriesgar. El coste de un fallo viene dado por la ruta: quedarse al principio, retroceder una pregunta o cruzar un peaje hacia atrás. En media, fallar en roja o negra obliga a confirmar el peaje anterior y volver a redonda o picuda. El coste es mayor que fallar en la primera posición.</p><p>En puntos, ese fallo suma uno y el cruce hacia atrás suma dos más. En cooperativo, cuenta para el límite de seis fallos. La elección con más cartas favorables sigue siendo razonable; una probabilidad alta no elimina esos costes si sale una carta desfavorable.</p></section>
    <section><h2>Decisiones de grupo que sí puedes controlar</h2><h3>Dos jugadores con validación verbal</h3><p>Decidid y pronunciad la respuesta antes de revelar. El preguntador marca si hubo acierto; la web no comprueba la frase. Acordad también que los empates son fallos para que la validación siga la misma regla que el modo automático.</p><h3>La patata y el pase</h3><p>Cuando un acierto habilita el pase, puedes elegir destinatario o mantener el móvil. Esto cambia quién responde, no la baraja ni la posición. Cruzar un peaje no permite saltarse su confirmación. Si habéis pactado igualdad de participación, pasad a quien lleve menos intervenciones; la web no lleva ese reparto por vosotros.</p><h3>Comparar resultados con sentido</h3><p>Dos partidas usan barajas distintas. Para una competición, mantened variante y dificultad y acordad cómo registrar abandonos o mazos agotados. Una única victoria no demuestra que una persona tome mejores decisiones.</p></section>
    <section><h2>Un método breve para cada intento</h2><ol><li>Identifica la pregunta y su referencia, si la necesita.</li><li>Cuenta resultados favorables usando solo cartas realmente conocidas.</li><li>Elige la opción más probable y acepta que puede fallar.</li><li>Tras revelar, actualiza el historial; tras un peaje, sigue sin añadir una carta al recuento.</li></ol><p>La <Link prefetch={false} href="/probabilidades">tabla de probabilidades y su metodología</Link> desarrolla los cálculos. Las <Link prefetch={false} href="/variantes">variantes de sesión</Link> ayudan a acordar objetivos sin modificar el motor.</p></section>
  </EditorialArticle>;
}
